name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        # build it, give it a secret that is defined in github repo secrets so we can have use a PAT that has permission to pull the resume repo.  
        docker build . --build-arg PAT=${{ secrets.PAT }} -t ghcr.io/blademccool/chws-website:${{ github.sha }}
        docker tag ghcr.io/blademccool/chws-website:${{ github.sha }} ghcr.io/blademccool/chws-website:latest
        docker push ghcr.io/blademccool/chws-website:${{ github.sha }}
        docker push ghcr.io/blademccool/chws-website:latest
