name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [ subcomponent_updated ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.WRITE_REGISTRY_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # build it - i seemed to get an error with cross repo registry stuff using the GITHUB_TOKEN var for the pw in the registry login above, so i set up a PAT that definitely has permission and it seems to work for all the operations. meh
    - name: Build and push Docker image
      run: |
        docker build . -t ghcr.io/blademccool/chws-website:${{ github.sha }}
        docker tag ghcr.io/blademccool/chws-website:${{ github.sha }} ghcr.io/blademccool/chws-website:latest
        docker push ghcr.io/blademccool/chws-website:${{ github.sha }}
        docker push ghcr.io/blademccool/chws-website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' #do not deploy in PRs that are not merged!
    steps:
      # deploy using our hosted app id in digital ocean app platform, using the digital ocean pat we created in our account over there.
      # app id bb3fe71e-b9c2-4163-aca2-1d6dd0ac4c02 is our website component in digital ocean app platform.
    - name: Deploy
      run: >
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DIGITAL_OCEAN_PAT }}" \
          "https://api.digitalocean.com/v2/apps/bb3fe71e-b9c2-4163-aca2-1d6dd0ac4c02/deployments"